spring:
  data:
    mongodb:
      uri: mongodb+srv://unified:unified2022@unified-social-media.vqpowkx.mongodb.net/unified?retryWrites=true&w=majority
server:
  port: ${PORT:8080}
  servlet:
    context-path: /unified
